; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "facetracker"
#define MyAppVersion "1.0.0.0"
#define MyAppPublisher "DiacareSoft"
#define MyAppExeName "facetracker.exe"

#define Opencv "C:\Programming\3rdParties\opencv310"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{874CF2E5-2F39-4964-B6BC-2C60E986C3E9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName=FRTools
OutputDir=C:\Programming\Releases
OutputBaseFilename=SETUP_{#MyAppName}_{#MyAppVersion}
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "C:\Programming\ofrt\facetracker\build\build-test-Desktop_Qt_5_5_1_MSVC2013_32bit-Release\release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_frontalface_alt.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_frontalface_alt2.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_frontalface_alt_tree.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_frontalface_default.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_fullbody.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_upperbody.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_eye_tree_eyeglasses.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\haarcascades\haarcascade_eye.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\sources\data\lbpcascades\lbpcascade_frontalface.xml"; DestDir: "{app}\haarcascades"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_core310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_face310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_ffmpeg310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_highgui310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_imgcodecs310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_imgproc310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_objdetect310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_video310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_videoio310.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#Opencv}\build\x86\vc12\bin\opencv_ml310.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
; Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
; Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

